# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu.xdc

# IP: ip/instr_mem_1/instr_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==instr_mem || ORIG_REF_NAME==instr_mem} -quiet] -quiet
