# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu.xdc

# IP: ip/clk_wiz/clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] -quiet
