# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/Jaredan/CS214/Project/verilog/project_3/CS214-Project-CPU.srcs/sources_1/ip/instr_mem_1/instr_mem.xci
# IP: The module: 'instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/Jaredan/CS214/Project/verilog/project_3/CS214-Project-CPU.srcs/sources_1/ip/instr_mem_1/instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ubuntu/Jaredan/CS214/Project/verilog/project_3/CS214-Project-CPU.srcs/sources_1/ip/instr_mem_1/instr_mem.xci
# IP: The module: 'instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/Jaredan/CS214/Project/verilog/project_3/CS214-Project-CPU.srcs/sources_1/ip/instr_mem_1/instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
