# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/SUSTech/02Sophomore/DigitalDesign/CS214-Project-CPU-debug/CS214-Project-CPU.srcs/sources_1/ip/dmem_uram_1/dmem_uram.xci
# IP: The module: 'dmem_uram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SUSTech/02Sophomore/DigitalDesign/CS214-Project-CPU-debug/CS214-Project-CPU.srcs/sources_1/ip/dmem_uram_1/dmem_uram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem_uram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/SUSTech/02Sophomore/DigitalDesign/CS214-Project-CPU-debug/CS214-Project-CPU.srcs/sources_1/ip/dmem_uram_1/dmem_uram.xci
# IP: The module: 'dmem_uram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SUSTech/02Sophomore/DigitalDesign/CS214-Project-CPU-debug/CS214-Project-CPU.srcs/sources_1/ip/dmem_uram_1/dmem_uram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem_uram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
