set_property IOSTANDARD LVCMOS33 [get_ports *]
create_clock -period 10 [get_ports fpga_clk]
set_property PACKAGE_PIN P17 [get_ports fpga_clk]
set_property PACKAGE_PIN P15 [get_ports fpga_rst_n]

set_property PACKAGE_PIN N5 [get_ports uart_rx]
set_property PACKAGE_PIN T4 [get_ports uart_tx]

set_property PACKAGE_PIN R1 [get_ports {sw_l[0]}]
set_property PACKAGE_PIN N4 [get_ports {sw_l[1]}]
set_property PACKAGE_PIN M4 [get_ports {sw_l[2]}]
set_property PACKAGE_PIN R2 [get_ports {sw_l[3]}]
set_property PACKAGE_PIN P2 [get_ports {sw_l[4]}]
set_property PACKAGE_PIN P3 [get_ports {sw_l[5]}]
set_property PACKAGE_PIN P4 [get_ports {sw_l[6]}]
set_property PACKAGE_PIN P5 [get_ports {sw_l[7]}]

set_property PACKAGE_PIN T5 [get_ports {sw_r[0]}]
set_property PACKAGE_PIN T3 [get_ports {sw_r[1]}]
set_property PACKAGE_PIN R3 [get_ports {sw_r[2]}]
set_property PACKAGE_PIN V4 [get_ports {sw_r[3]}]
set_property PACKAGE_PIN V5 [get_ports {sw_r[4]}]
set_property PACKAGE_PIN V2 [get_ports {sw_r[5]}]
set_property PACKAGE_PIN U2 [get_ports {sw_r[6]}]
set_property PACKAGE_PIN U3 [get_ports start_pg]

set_property PACKAGE_PIN K2 [get_ports {led_l[0]}]
set_property PACKAGE_PIN J2 [get_ports {led_l[1]}]
set_property PACKAGE_PIN J3 [get_ports {led_l[2]}]
set_property PACKAGE_PIN H4 [get_ports {led_l[3]}]
set_property PACKAGE_PIN J4 [get_ports {led_l[4]}]
set_property PACKAGE_PIN G3 [get_ports {led_l[5]}]
set_property PACKAGE_PIN G4 [get_ports {led_l[6]}]
set_property PACKAGE_PIN F6 [get_ports {led_l[7]}]

set_property PACKAGE_PIN K3 [get_ports {led_r[0]}]
set_property PACKAGE_PIN M1 [get_ports {led_r[1]}]
set_property PACKAGE_PIN L1 [get_ports {led_r[2]}]
set_property PACKAGE_PIN K6 [get_ports {led_r[3]}]
set_property PACKAGE_PIN J5 [get_ports {led_r[4]}]
set_property PACKAGE_PIN H5 [get_ports {led_r[5]}]
set_property PACKAGE_PIN H6 [get_ports {led_r[6]}]
set_property PACKAGE_PIN K1 [get_ports {led_r[7]}]

set_property PACKAGE_PIN R15 [get_ports but_center]

# tub_signal
set_property PACKAGE_PIN B4 [get_ports {tub_data1[7]}]
set_property PACKAGE_PIN A4 [get_ports {tub_data1[6]}]
set_property PACKAGE_PIN A3 [get_ports {tub_data1[5]}]
set_property PACKAGE_PIN B1 [get_ports {tub_data1[4]}]
set_property PACKAGE_PIN A1 [get_ports {tub_data1[3]}]
set_property PACKAGE_PIN B3 [get_ports {tub_data1[2]}]
set_property PACKAGE_PIN B2 [get_ports {tub_data1[1]}]
set_property PACKAGE_PIN D5 [get_ports {tub_data1[0]}]
set_property PACKAGE_PIN D4 [get_ports {tub_data2[7]}]
set_property PACKAGE_PIN E3 [get_ports {tub_data2[6]}]
set_property PACKAGE_PIN D3 [get_ports {tub_data2[5]}]
set_property PACKAGE_PIN F4 [get_ports {tub_data2[4]}]
set_property PACKAGE_PIN F3 [get_ports {tub_data2[3]}]
set_property PACKAGE_PIN E2 [get_ports {tub_data2[2]}]
set_property PACKAGE_PIN D2 [get_ports {tub_data2[1]}]
set_property PACKAGE_PIN H2 [get_ports {tub_data2[0]}]
set_property PACKAGE_PIN G2 [get_ports {tub_sel[7]}]
set_property PACKAGE_PIN C2 [get_ports {tub_sel[6]}]
set_property PACKAGE_PIN C1 [get_ports {tub_sel[5]}]
set_property PACKAGE_PIN H1 [get_ports {tub_sel[4]}]
set_property PACKAGE_PIN G1 [get_ports {tub_sel[3]}]
set_property PACKAGE_PIN F1 [get_ports {tub_sel[2]}]
set_property PACKAGE_PIN E1 [get_ports {tub_sel[1]}]
set_property PACKAGE_PIN G6 [get_ports {tub_sel[0]}]

set_property PACKAGE_PIN V1 [get_ports {upg_rst_raw}]
